package net.nikaal.mhamod.datagen;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.nikaal.mhamod.MHAMod;
import net.nikaal.mhamod.item.ModItems;
import net.nikaal.mhamod.util.ModTags;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModItemTagProvider extends ItemTagsProvider {

    public ModItemTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, CompletableFuture<TagLookup<Block>> blockTags, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, blockTags, MHAMod.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider provider) {
        tag(ModTags.Items.MHAMOD_ITEMS)
                .add(ModItems.ADVENTURER_COMPASS.get())
                .add(ModItems.BEARING.get())
                .add(ModItems.CASING.get())
                .add(ModItems.CELL.get())
                .add(ModItems.DIAL.get())
                .add(ModItems.GEAR.get())
                .add(ModItems.LENS.get())
                .add(ModItems.NEEDLE.get())
                .add(ModItems.PIVOT.get())
                .add(ModItems.SCREW.get())
                .add(ModItems.ENCODED_TREASURE_MAP.get())
                .add(ModItems.MAP_PIECE_1.get())
                .add(ModItems.MAP_PIECE_2.get())
                .add(ModItems.MAP_PIECE_3.get())
                .add(ModItems.MAP_PIECE_4.get())
                .add(ModItems.MAP_PIECE_5.get())
                .add(ModItems.MAP_PIECE_6.get())
                .add(ModItems.MAP_PIECE_7.get())
                .add(ModItems.MAP_PIECE_8.get())
                .add(ModItems.MAP_PIECE_9.get())
                .add(ModItems.AELWYN_TROPHY.get())
                .add(ModItems.CONJONCTIVIX_TROPHY.get())
                .add(ModItems.DEEZ_TROPHY.get())
                .add(ModItems.HEAVENLORD_TROPHY.get())
                .add(ModItems.IPLAY4YOU_TROPHY.get())
                .add(ModItems.JOLIROUGE_TROPHY.get())
                .add(ModItems.LUDOLIK_TROPHY.get())
                .add(ModItems.MAESTROMM_TROPHY.get())
                .add(ModItems.MIKEFRAISE_TROPHY.get())
                .add(ModItems.MISTERX_TROPHY.get())
                .add(ModItems.NICODELPRA_TROPHY.get())
                .add(ModItems.SORAX_TROPHY.get())
                .add(ModItems.SYMETRIX_TROPHY.get())
                .add(ModItems.VAYLE_TROPHY.get())
                .add(ModItems.RORSHAK_TROPHY.get())
                .add(ModItems.VICTORY_TROPHY.get())
                .add(ModItems.COCOLYNE_TROPHY.get())
                .add(ModItems.LAAKIN_TROPHY.get())
                .add(ModItems.NIKAAL_TROPHY.get())
                .add(ModItems.AELWYN_SPAWN_EGG.get())
                .add(ModItems.CONJONCTIVIX_SPAWN_EGG.get())
                .add(ModItems.DEEZ_SPAWN_EGG.get())
                .add(ModItems.HEAVENLORD_SPAWN_EGG.get())
                .add(ModItems.IPLAY4YOU_SPAWN_EGG.get())
                .add(ModItems.JOLIROUGE_SPAWN_EGG.get())
                .add(ModItems.LUDOLIK_SPAWN_EGG.get())
                .add(ModItems.MAESTROMM_SPAWN_EGG.get())
                .add(ModItems.MIKEFRAISE_SPAWN_EGG.get())
                .add(ModItems.MISTERX_SPAWN_EGG.get())
                .add(ModItems.NICODELPRA_SPAWN_EGG.get())
                .add(ModItems.PETLEFEU_SPAWN_EGG.get())
                .add(ModItems.PIMPRY_SPAWN_EGG.get())
                .add(ModItems.RORSHAK_SPAWN_EGG.get())
                .add(ModItems.SORAX_SPAWN_EGG.get())
                .add(ModItems.SYMETRIX_SPAWN_EGG.get())
                .add(ModItems.TOADY_SPAWN_EGG.get())
                .add(ModItems.VAYLE_SPAWN_EGG.get())
                .add(ModItems.NIKAAL_SPAWN_EGG.get())
                .add(ModItems.COCOLYNE_SPAWN_EGG.get())
                .add(ModItems.LAAKIN_SPAWN_EGG.get());
        tag(ModTags.Items.POTC_ITEMS)
                .add(ModItems.ADVENTURER_COMPASS.get())
                .add(ModItems.BEARING.get())
                .add(ModItems.CASING.get())
                .add(ModItems.CELL.get())
                .add(ModItems.DIAL.get())
                .add(ModItems.GEAR.get())
                .add(ModItems.LENS.get())
                .add(ModItems.NEEDLE.get())
                .add(ModItems.PIVOT.get())
                .add(ModItems.SCREW.get())
                .add(ModItems.ENCODED_TREASURE_MAP.get())
                .add(ModItems.MAP_PIECE_1.get())
                .add(ModItems.MAP_PIECE_2.get())
                .add(ModItems.MAP_PIECE_3.get())
                .add(ModItems.MAP_PIECE_4.get())
                .add(ModItems.MAP_PIECE_5.get())
                .add(ModItems.MAP_PIECE_6.get())
                .add(ModItems.MAP_PIECE_7.get())
                .add(ModItems.MAP_PIECE_8.get())
                .add(ModItems.MAP_PIECE_9.get());
        tag(ModTags.Items.POTC_MAP_PIECES)
                .add(ModItems.ENCODED_TREASURE_MAP.get())
                .add(ModItems.MAP_PIECE_1.get())
                .add(ModItems.MAP_PIECE_2.get())
                .add(ModItems.MAP_PIECE_3.get())
                .add(ModItems.MAP_PIECE_4.get())
                .add(ModItems.MAP_PIECE_5.get())
                .add(ModItems.MAP_PIECE_6.get())
                .add(ModItems.MAP_PIECE_7.get())
                .add(ModItems.MAP_PIECE_8.get())
                .add(ModItems.MAP_PIECE_9.get());
        tag(ModTags.Items.POTC_COMPASS_PIECES)
                .add(ModItems.ADVENTURER_COMPASS.get())
                .add(ModItems.BEARING.get())
                .add(ModItems.CASING.get())
                .add(ModItems.CELL.get())
                .add(ModItems.DIAL.get())
                .add(ModItems.GEAR.get())
                .add(ModItems.LENS.get())
                .add(ModItems.NEEDLE.get())
                .add(ModItems.PIVOT.get())
                .add(ModItems.SCREW.get());
        tag(ModTags.Items.MHAMOD_TROPHIES)
                .add(ModItems.AELWYN_TROPHY.get())
                .add(ModItems.CONJONCTIVIX_TROPHY.get())
                .add(ModItems.DEEZ_TROPHY.get())
                .add(ModItems.HEAVENLORD_TROPHY.get())
                .add(ModItems.IPLAY4YOU_TROPHY.get())
                .add(ModItems.JOLIROUGE_TROPHY.get())
                .add(ModItems.LUDOLIK_TROPHY.get())
                .add(ModItems.MAESTROMM_TROPHY.get())
                .add(ModItems.MIKEFRAISE_TROPHY.get())
                .add(ModItems.MISTERX_TROPHY.get())
                .add(ModItems.NICODELPRA_TROPHY.get())
                .add(ModItems.SORAX_TROPHY.get())
                .add(ModItems.SYMETRIX_TROPHY.get())
                .add(ModItems.VAYLE_TROPHY.get())
                .add(ModItems.RORSHAK_TROPHY.get())
                .add(ModItems.VICTORY_TROPHY.get())
                .add(ModItems.COCOLYNE_TROPHY.get())
                .add(ModItems.LAAKIN_TROPHY.get())
                .add(ModItems.NIKAAL_TROPHY.get());
        tag(ModTags.Items.MHAMOD_SPAWN_EGGS)
                .add(ModItems.AELWYN_SPAWN_EGG.get())
                .add(ModItems.CONJONCTIVIX_SPAWN_EGG.get())
                .add(ModItems.DEEZ_SPAWN_EGG.get())
                .add(ModItems.HEAVENLORD_SPAWN_EGG.get())
                .add(ModItems.IPLAY4YOU_SPAWN_EGG.get())
                .add(ModItems.JOLIROUGE_SPAWN_EGG.get())
                .add(ModItems.LUDOLIK_SPAWN_EGG.get())
                .add(ModItems.MAESTROMM_SPAWN_EGG.get())
                .add(ModItems.MIKEFRAISE_SPAWN_EGG.get())
                .add(ModItems.MISTERX_SPAWN_EGG.get())
                .add(ModItems.NICODELPRA_SPAWN_EGG.get())
                .add(ModItems.PETLEFEU_SPAWN_EGG.get())
                .add(ModItems.PIMPRY_SPAWN_EGG.get())
                .add(ModItems.RORSHAK_SPAWN_EGG.get())
                .add(ModItems.SORAX_SPAWN_EGG.get())
                .add(ModItems.SYMETRIX_SPAWN_EGG.get())
                .add(ModItems.TOADY_SPAWN_EGG.get())
                .add(ModItems.VAYLE_SPAWN_EGG.get())
                .add(ModItems.NIKAAL_SPAWN_EGG.get())
                .add(ModItems.COCOLYNE_SPAWN_EGG.get())
                .add(ModItems.LAAKIN_SPAWN_EGG.get());
    }
}
